# Generated by Django 6.0.5 on 2026-06-30 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('instructor', models.CharField(max_length=100)),
                ('horas_duracion', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('foto', models.FileField(blank=True, null=True, upload_to='tecnicos')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('APROBADO', 'Aprobado'), ('REPROBADO', 'Reprobado')], default='EN_CURSO', max_length=10)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnologia.curso')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnologia.tecnico')),
            ],
        ),
    ]
